config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  resources :restaurants do
    collection do
      post :search, as: :search
      post :filter, as: :filter
    end
    resources :attachments
  end

  get 'pages/index'

end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  belongs_to :restaurant

  has_attached_file :file, styles: { thumb: "100x100>" }

  validates_attachment :file, presence: true,
    content_type: { content_type: /\Aimage\/.*\Z/ }
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :attachments

  accepts_nested_attributes_for :attachments

  validates :zomato_id, presence: true, uniqueness: true

  scope :attachs, -> { joins(:attachments).includes(:attachments) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  respond_to :js

  def search
    fetch_restaurants
    save_search_params
    @rests = clean_restaurants
    fill_restaurant_models @rests
  end

  def filter
    bookmark_ids = ZomatoApi::Restaurants.bookmarks
    @to_remove = params[:shown_ids].split(',') - bookmark_ids
  end

  def create
    Restaurant.create! restaurant_params
    redirect_to :root
  end

  def update
    Restaurant.find(params[:id]).update! restaurant_params
    redirect_to :root
  end

  private

  def save_search_params
    sp = search_params
    cookies.signed['last-query'] = sp[:query]
    cookies.signed['last-lat'] = sp[:latitude]
    cookies.signed['last-lon'] = sp[:longitude]
  end

  def fill_restaurant_models rests
    saved = Restaurant.where(zomato_id: @rests.map { |r| r['id'] }).attachs
      .inject({}) do |ret, r|
        ret.merge({ r.zomato_id => r })
      end

    rests.each do |r|
      r['rest_obj'] = saved[r['id']] || Restaurant.new
      r['rest_obj'].attachments.build
    end
  end

  def fetch_restaurants
    @zomato_restaurants = JSON.parse ZomatoApi::Restaurants.search search_params
  end

  def clean_restaurants
    @zomato_restaurants['restaurants'].map { |r| r['restaurant'] }
  end

  def search_params
    ps = query_params
    ps[:limit] ||= 20
    ps
  end

  def query_params
    params.permit :query, :latitude, :longitude
  end

  def restaurant_params
    params.require(:restaurant)
      .permit(:zomato_id, :text_notes, attachments_attributes: :file)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  def last_query
    cookies.signed['last-query']
  end

  def last_latitude
    cookies.signed['last-lat']
  end

  def last_longitude
    cookies.signed['last-lon']
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zomato</title>
  <script>window.zmt = {};</script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/pages/index.html.haml
.row
  .col-xs-12.text-center
    %h1 Zomato Attach

    = form_tag search_restaurants_path, method: :post, remote: true do
      = text_field_tag :query, nil, id: 'restaurant-search', class: 'form-control', placeholder: 'search', value: last_query
      = number_field_tag :latitude, nil, id: 'latitude', hidden: true, value: last_latitude
      = number_field_tag :longitude, nil, id: 'longitude', hidden: true, value: last_longitude

    = form_tag filter_restaurants_path, method: :post, remote: true do
      = text_field_tag :shown_ids, nil, id: 'filter-restaurants-input', hidden: true
      = submit_tag 'Filter Bookmarks', class: 'btn btn-default btn-primary'

    %button.btn.btn-success.btn-s.hidden#clear-filter
      = fa_icon 'refresh'

.row.text-center#main-spinner
  .col-xs-12
    = image_tag asset_path('spinner.svg')

.row
  .col-xs-12
    #restaurant-list-container

app/views/restaurants/_restaurant_badge.haml
.restaurant-container{ id: "restaurant-container-for-#{restaurant['id']}" }
  .row
    .col-xs-2
      %img.img-responsive.img-thumbnail{ src: restaurant['thumb'] }
    .col-xs-10
      %h4
        = link_to restaurant['name'], restaurant['url'], target: '_blank', class: 'zomato-link'
      %p
        %b Neighborhood:
        = restaurant['location']['locality']
      %p
        %b Cuisines:
        = succeed '.' do
          = restaurant['cuisines']
      %p
        %b Price Range:
        = restaurant['currency'] * restaurant['price_range'].to_i
      %p
        %b Average Rating:
        = restaurant['user_rating']['rating_text']
        = succeed ')' do
          = "(#{restaurant['user_rating']['aggregate_rating']}"

  .row
    .col-xs-12
      .hr
      .row
        .col-xs-6.attachment-container{ id: "#{restaurant['id']}-image-container" }
          %b Image Notes
          %br
          - restaurant['rest_obj'].attachments.each do |att|
            - if att.file.present?
              %a.attachment-popup-link{ href: att.file.url }
                = image_tag att.file.url(:thumb), class: 'img-thumbnail'
        .col-xs-6.text-notes-container.clearfix{ id: "#{restaurant['id']}-text-notes-container" }
          %b Text Notes
          %br
          = form_for restaurant['rest_obj'], remote: true, html: {  } do |rf|
            = rf.text_area :text_notes, placeholder: 'Awesome Shrimp!'
            = rf.submit 'Update Text Note'
      .row
        .col-xs-6
          = form_for restaurant['rest_obj'], html: { multipart: true, class: 'form-inline' } do |rf|
            = rf.text_field :zomato_id, hidden: true, value: restaurant['id']
            = rf.fields_for :attachments do |af|
              - unless af.object.persisted?
                %span.btn.btn-primary.btn-default.btn-file
                  Attach...
                  = af.file_field :file
                %button.btn.btn-primary.btn-m.hidden{ type: 'submit' }
                  = fa_icon 'upload'

app/views/restaurants/attachments.html.erb
<h1>Restaurants#attachments</h1>
<p>Find me in app/views/restaurants/attachments.html.erb</p>